version: '3'

services:
  nodejs:
    image: task-project
    container_name: nodejs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app

